# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qusetion',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
